# =============================================================================
# Cleanup Old Figures Script
# =============================================================================
# This script removes figures that are not relevant to the research question
# Run after generating focused figures with 03_eda_focused.R
# =============================================================================

cat("\n=== Cleaning Up Old Figures ===\n\n")

figures_dir <- here("figures")

# List of figures to DELETE (not relevant to research question)
files_to_delete <- c(
  # Dimensions plots
  "accident_01_dimensions.png",
  "accident_event_01_dimensions.png",
  "accident_location_01_dimensions.png",
  "atmospheric_cond_01_dimensions.png",
  "node_01_dimensions.png",
  "person_01_dimensions.png",
  "road_surface_cond_01_dimensions.png",
  "sub_dca_01_dimensions.png",
  
  # Missing data visualizations
  "accident_02_missing_data.png",
  "accident_event_02_missing_data.png",
  "accident_location_02_missing_data.png",
  "node_02_missing_data.png",
  "person_02_missing_data.png",
  
  # Generic histograms
  "accident_03_hist_accident_type.png",
  "accident_03_hist_day_of_week.png",
  "accident_03_hist_dca_code.png",
  "accident_03_hist_light_condition.png",
  "accident_03_hist_node_id.png",
  "accident_event_03_hist_event_seq_no.png",
  "accident_location_03_hist_distance_location.png",
  "accident_location_03_hist_node_id.png",
  "accident_location_03_hist_road_route_1.png",
  "node_03_hist_amg_x.png",
  "node_03_hist_amg_y.png",
  "node_03_hist_latitude.png",
  "node_03_hist_longitude.png",
  "node_03_hist_node_id.png",
  "person_03_hist_ejected_code.png",
  "person_03_hist_helmet_belt_worn.png",
  "person_03_hist_inj_level.png",
  "person_03_hist_road_user_type.png",
  "atmospheric_cond_03_hist_atmosph_cond_seq.png",
  "atmospheric_cond_03_hist_atmosph_cond.png",
  "road_surface_cond_03_hist_surface_cond_seq.png",
  "road_surface_cond_03_hist_surface_cond.png",
  "sub_dca_03_hist_sub_dca_seq.png",
  
  # Generic bar plots (replaced by focused versions)
  "accident_04_bar_accident_type_desc.png",
  "accident_04_bar_day_week_desc.png",
  "accident_04_bar_rma.png",
  "accident_04_bar_road_geometry_desc.png",
  "accident_04_bar_speed_zone.png",
  "accident_event_04_bar_event_type_desc.png",
  "accident_event_04_bar_event_type.png",
  "accident_event_04_bar_vehicle_1_coll_pt_desc.png",
  "accident_event_04_bar_vehicle_1_coll_pt.png",
  "accident_event_04_bar_vehicle_2_coll_pt.png",
  "accident_location_04_bar_direction_location.png",
  "atmospheric_cond_04_bar_atmosph_cond_desc.png",
  "node_04_bar_deg_urban_name.png",
  "node_04_bar_node_type.png",
  "person_04_bar_age_group.png",
  "person_04_bar_inj_level_desc.png",
  "person_04_bar_road_user_type_desc.png",
  "person_04_bar_seating_position.png",
  "person_04_bar_sex.png",
  "road_surface_cond_04_bar_surface_cond_desc.png",
  
  # Correlation matrices
  "accident_06_correlation.png",
  "accident_location_06_correlation.png",
  "atmospheric_cond_06_correlation.png",
  "node_06_correlation.png",
  "person_06_correlation.png",
  "road_surface_cond_06_correlation.png",
  
  # Summary stats for tables not in use
  "accident_event_05_summary_stats.txt",
  "sub_dca_05_summary_stats.txt"
)

# Delete files
deleted_count <- 0
not_found_count <- 0

for (file in files_to_delete) {
  file_path <- here(figures_dir, file)
  if (file.exists(file_path)) {
    file.remove(file_path)
    deleted_count <- deleted_count + 1
    cat("  Deleted:", file, "\n")
  } else {
    not_found_count <- not_found_count + 1
  }
}

cat("\n=== Cleanup Complete ===\n")
cat("Deleted:", deleted_count, "files\n")
if (not_found_count > 0) {
  cat("Not found (may have already been deleted):", not_found_count, "files\n")
}
cat("\nNote: Missing data summary CSVs and some summary stats are kept for reference.\n")
cat("Focus on the new figures generated by 03_eda_focused.R\n\n")

